logging:
  level:
    root: OFF
    org.springframework: OFF
    org.apache: OFF
    kafka: OFF

# https://stackoverflow.com/questions/50509743/can-we-disable-log4j-logs-only-for-kafka/62401824#62401824
# Add a logback.xml file in your resources dir:
# Add configs in application.yml/properties: